name: flutter_flux_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_flux:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
