# Important: Use "flutter packages get", not "pub get".
name: flutter_flux
author: Flutter Authors <flutter-dev@googlegroups.com>
version: 4.1.3
description: Flux library for Flutter, featuring unidirectional dataflow inspired by reflux and Facebook's flux architecture.
homepage: https://github.com/google/flutter_flux
dependencies:
  meta: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  quiver: '>=2.0.0 <3.0.0'
  test: ^1.5.1
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  

environment:
  sdk: ">=1.24.0 <3.0.0"
